export interface Programme {
  id: string;
  slug: string;
  title: string;
  category: string;
  categorySlug: string;
  slogan: string;
  description: string;
  objectif: string;
  publicVise: string;
  impact: string;
  image: string;
  startDate: string;
  endDate: string;
  startTime: string;
  endTime: string;
  location: string;
  discipline: string;
  featured?: boolean;
}

export const categories = [
  {
    id: "musique-arts-vivants",
    title: "Musique & Arts vivants",
    description:
      "Célébration de la richesse musicale et des performances scéniques congolaises",
    image: "/images/events/event1.jpg",
    color: "from-red-600 to-orange-600",
  },
  {
    id: "theatre-arts-scene",
    title: "Théâtre & Arts de la scène",
    description:
      "En novembre, dix jours de célébration réunissant troupes locales et internationales.",
    image: "/images/events/event2.jpg",
    color: "from-purple-600 to-pink-600",
  },
  {
    id: "cinema-audiovisuel",
    title: "Cinéma & Audiovisuel",
    description:
      "Valorisation du cinéma et de la création audiovisuelle congolaise",
    image: "/images/media/cinema.jpg",
    color: "from-blue-600 to-cyan-600",
  },
  {
    id: "litterature-pensee",
    title: "Littérature & Pensée",
    description:
      "Préservation et transmission du patrimoine culturel et littéraire",
    image: "/images/media/media7.jpg",
    color: "from-green-600 to-teal-600",
  },
];

export const programmes: Programme[] = [
  // Cinéma & Audiovisuel

  // {
  //   id: "13",
  //   slug: "kelasi-film-festival",
  //   title: "Kelasi Film Festival",
  //   category: "Cinéma & Audiovisuel",
  //   categorySlug: "cinema-audiovisuel",
  //   slogan: "Cinéma jeune pour la jeunesse",
  //   description:
  //     "Festival international du film éducatif et citoyen, au service de la jeunesse et de l’apprentissage.",
  //   objectif: "Encourager l'émergence de nouveaux talents cinématographiques",
  //   publicVise: "Jeunes réalisateurs, étudiants, public jeune",
  //   impact: "Formation et accompagnement de la nouvelle génération",
  //   image: "/images/media/media10.jpg",
  //   startDate: "2025-12-15",
  //   endDate: "2025-12-15",
  //   startTime: "14:00",
  //   endTime: "16:00",
  //   location: "Salle de Danse Principale",
  //   discipline: "Atelier",
  //   featured: true,
  // },
  {
    id: "11",
    slug: "cinematheque-congolaise",
    title: "Cinémathèque congolaise",
    category: "Cinéma & Audiovisuel",
    categorySlug: "cinema-audiovisuel",
    slogan: "Mémoire du cinéma congolais",
    description:
      "Chaque semaine, diffusion d’œuvres congolaises pour valoriser le cinéma national et assurer sa circulation.",
    objectif: "Préserver et valoriser l'histoire du cinéma congolais",
    publicVise: "Cinéphiles, chercheurs, étudiants en cinéma",
    impact: "Sauvegarde de films historiques et éducation cinématographique",
    image: "/images/media/media11.jpg",
    startDate: "2025-12-15",
    endDate: "2025-12-15",
    startTime: "14:00",
    endTime: "16:00",
    location: "Salle de Danse Principale",
    featured: true,
    discipline: "Atelier",
  },
  {
    id: "12",
    slug: "festival-kasala",
    title: " Festival KASALA",
    category: "Cinéma & Audiovisuel",
    categorySlug: "cinema-audiovisuel",
    slogan: "Documentaires du Congo et d’Afrique",
    description:
      "Programme dédié au documentaire congolais et africain, avec résidences, ateliers et projections.",
    objectif: "Promouvoir la production cinématographique africaine",
    publicVise: "Réalisateurs, producteurs, distributeurs, grand public",
    impact: "Visibilité internationale du cinéma africain",
    image: "/images/media/media9.jpg",
    startDate: "2025-12-15",
    endDate: "2025-12-15",
    startTime: "14:00",
    endTime: "16:00",
    location: "Salle de Danse Principale",
    discipline: "Atelier",
  },
  {
    id: "14",
    slug: "coproductions-audiovisuel",
    title: "Coproductions & diffusion audiovisuelle",
    category: "Cinéma & Audiovisuel",
    categorySlug: "cinema-audiovisuel",
    slogan: "Soutien à la création audiovisuelle",
    description:
      "Soutien à la création et à la circulation des œuvres audiovisuelles.",
    objectif: "Faciliter la production et la diffusion d'œuvres audiovisuelles",
    publicVise: "Producteurs, réalisateurs, diffuseurs",
    impact: "Augmentation de la production audiovisuelle nationale",
    image: "/images/events/event1.jpg",
    startDate: "2025-12-15",
    endDate: "2025-12-15",
    startTime: "14:00",
    endTime: "16:00",
    location: "Salle de Danse Principale",
    discipline: "Atelier",
  },

  // Musique & Arts vivants

  {
    id: "1",
    slug: "missa-congo",
    title: "Missa Congo",
    category: "Musique & Arts vivants",
    categorySlug: "musique-arts-vivants",
    slogan: "La messe congolaise qui unit tradition et spiritualité",
    description:
      "Un grand concert caritatif avec la Fondation Joseph Diangienda Kutima et l&apos;Orchestre Symphonique Kimbanguiste. Acte de mémoire, solidarité et élévation spirituelle par la musique. ",
    objectif:
      "Valoriser la musique sacrée congolaise et créer un pont entre tradition religieuse et culture locale",
    publicVise: "Communautés religieuses, mélomanes, chercheurs en musicologie",
    impact:
      "Reconnaissance internationale de la Missa Congo comme patrimoine culturel immatériel",
    image: "/images/events/event1.jpg",
    startDate: "2025-12-15",
    endDate: "2025-12-15",
    startTime: "14:00",
    endTime: "16:00",
    location: "Salle de Danse Principale",
    discipline: "Atelier",
  },
  {
    id: "2",
    slug: "hommage-a-papa-wemba",
    title: "Hommage à Papa Wemba ",
    category: "Musique & Arts vivants",
    categorySlug: "musique-arts-vivants",
    slogan: "Hommage au roi de la rumba congolaise",
    description:
      "En avril, concerts, expositions et concours célèbrent l’œuvre et l’héritage du chanteur.",
    objectif:
      "Perpétuer la mémoire et l'influence de Papa Wemba dans la musique africaine",
    publicVise: "Fans de rumba, jeunes artistes, public international",
    impact: "Transmission de l'héritage musical aux nouvelles générations",
    image: "/images/events/papa-wemba.jpg",
    startDate: "2025-12-15",
    endDate: "2025-12-15",
    startTime: "14:00",
    endTime: "16:00",
    location: "Salle de Danse Principale",
    discipline: "Atelier",
    featured: true,
  },
  {
    id: "3",
    slug: "african-fiesta-guitare-festival",
    title: "African Fiesta Guitare Festival",
    category: "Musique & Arts vivants",
    categorySlug: "musique-arts-vivants",
    slogan: "La guitare africaine à l'honneur",
    description:
      "Un festival dédié à la guitare congolaise et africaine, emblème de la rumba.",
    objectif:
      "Promouvoir l'excellence guitaristique africaine et créer des échanges entre musiciens",
    publicVise: "Guitaristes, musiciens, amateurs de musique africaine",
    impact:
      "Création d'un réseau de guitaristes africains et formation de jeunes talents",
    image: "/images/events/event1.jpg",
    startDate: "2025-12-15",
    endDate: "2025-12-15",
    startTime: "14:00",
    endTime: "16:00",
    location: "Salle de Danse Principale",
    discipline: "Atelier",
  },
  {
    id: "4",
    slug: "maitre-rumba",
    title: "Le Maître de la Rumba",
    category: "Musique & Arts vivants",
    categorySlug: "musique-arts-vivants",
    slogan: "Retraçant l’odyssée culturelle des racines congolaises",
    description:
      "Festival bi-annuel retraçant l’odyssée culturelle des racines congolaises, symbole des liens avec la diaspora.",
    objectif: "Documenter et célébrer l'histoire de la rumba congolaise",
    publicVise: "Historiens de la musique, danseurs, public intergénérationnel",
    impact: "Préservation de la mémoire collective de la rumba",
    image: "/images/events/event1.jpg",
    startDate: "2025-12-15",
    endDate: "2025-12-15",
    startTime: "14:00",
    endTime: "16:00",
    location: "Salle de Danse Principale",
    discipline: "Atelier",
  },
  {
    id: "5",
    slug: "fete-musique",
    title: "Fête de la Musique, Autrement",
    category: "Musique & Arts vivants",
    categorySlug: "musique-arts-vivants",
    slogan: "La musique dans tous ses états",
    description:
      "Le 22 juin, une édition innovante, ouverte aux fusions musicales et talents émergents.",
    objectif: "Offrir une plateforme d'expression à tous les genres musicaux",
    publicVise: "Grand public, familles, artistes émergents",
    impact: "Démocratisation de l'accès à la culture musicale",
    image: "/images/events/event1.jpg",
    startDate: "2025-12-15",
    endDate: "2025-12-15",
    startTime: "14:00",
    endTime: "16:00",
    location: "Salle de Danse Principale",
    discipline: "Atelier",
  },

  // Théâtre & Arts de la scène
  {
    id: "6",
    slug: "dramatheque-congolaise",
    title: "Dramathèque congolaise",
    category: "Théâtre & Arts de la scène",
    categorySlug: "theatre-arts-scene",
    slogan: "Dépôt de la culture théâtrale congolaise et africaine",
    description:
      "Programme permanent dédié aux dramaturges et comédiens congolais et africains.",
    objectif:
      "Constituer une bibliothèque vivante des œuvres théâtrales congolaises et internationales",
    publicVise: "Comédiens, metteurs en scène, chercheurs, étudiants",
    impact: "Préservation et accessibilité du patrimoine théâtral national",
    image: "/images/events/event1.jpg",
    startDate: "2025-12-15",
    endDate: "2025-12-15",
    startTime: "14:00",
    endTime: "16:00",
    location: "Salle de Danse Principale",
    featured: true,
    discipline: "Atelier",
  },
  {
    id: "7",
    slug: "festival-des-deux-rives",
    title: "Festival des Deux Rives",
    category: "Théâtre & Arts de la scène",
    categorySlug: "theatre-arts-scene",
    slogan: "Dialogue interculturel entre Kinshasa et Brazzaville",
    description:
      "Rencontre Kinshasa-Brazzaville, spectacles et ateliers favorisent un dialogue interculturel.",
    objectif: "Promouvoir la création théâtrale contemporaine congolaise",
    publicVise:
      "Professionnels du théâtre, public amateur, institutions culturelles",
    impact:
      "Structuration du secteur théâtral et émergence de nouveaux talents",
    image: "/images/events/event1.jpg",
    startDate: "2025-12-15",
    endDate: "2025-12-15",
    startTime: "14:00",
    endTime: "16:00",
    location: "Salle de Danse Principale",
    discipline: "Atelier",
  },
  // {
  //   id: "8",
  //   slug: "festival-maloba",
  //   title: "Festival Maloba",
  //   category: "Théâtre & Arts de la scène",
  //   categorySlug: "theatre-arts-scene",
  //   slogan: "La parole en action",
  //   description: "Festival dédié à l'art oratoire et à la performance verbale",
  //   objectif: "Valoriser l'art de la parole dans les traditions congolaises",
  //   publicVise: "Conteurs, slameurs, poètes, public jeune",
  //   impact: "Renouveau de l'art oratoire traditionnel",
  //   image: "/images/events/event1.jpg",
  //   startDate: "2025-12-15",
  //   endDate: "2025-12-15",
  //   startTime: "14:00",
  //   endTime: "16:00",
  //   location: "Salle de Danse Principale",
  //   discipline: "Atelier",
  // },
  {
    id: "9",
    slug: "rencontres-africaines-theatre",
    title: "Rencontres africaines du théâtre",
    category: "Théâtre & Arts de la scène",
    categorySlug: "theatre-arts-scene",
    slogan: "Le théâtre africain en dialogue",
    description:
      "En avril, dramaturges et comédiens de tout le continent se retrouvent au Centre.",
    objectif: "Créer un réseau panafricain de professionnels du théâtre",
    publicVise:
      "Professionnels du théâtre africain, programmateurs internationaux",
    impact: "Circulation des œuvres théâtrales africaines",
    image: "/images/events/event1.jpg",
    startDate: "2025-12-15",
    endDate: "2025-12-15",
    startTime: "14:00",
    endTime: "16:00",
    location: "Salle de Danse Principale",
    discipline: "Atelier",
  },
  {
    id: "10",
    slug: "au-temps-en-rire",
    title: "Au Temps en Rire",
    category: "Théâtre & Arts de la scène",
    categorySlug: "theatre-arts-scene",
    slogan: "Une scène vivante pour l’humour et la comédie",
    description:
      "Une programmation mensuelle dédiée à l’humour et à la comédie.",
    objectif: "Promouvoir l'humour comme vecteur de cohésion sociale",
    publicVise: "Grand public, familles, humoristes émergents",
    impact: "Professionnalisation du secteur de l'humour",
    image: "/images/events/event1.jpg",
    startDate: "2025-12-15",
    endDate: "2025-12-15",
    startTime: "14:00",
    endTime: "16:00",
    location: "Salle de Danse Principale",
    discipline: "Atelier",
  },

  // Littérature & Pensée
  {
    id: "15",
    slug: "nuit-poesie",
    title: "Nuit de la poésie",
    category: "Littérature & Pensée",
    categorySlug: "litterature-patrimoine",
    slogan: "La poésie en vers et en voix",
    description:
      "Chaque 21 mars, poètes et écrivains célèbrent la puissance de la parole à travers lectures et ateliers.",
    objectif: "Promouvoir la poésie comme art vivant et accessible",
    publicVise: "Poètes, étudiants, amateurs de littérature",
    impact: "Renouveau de l'intérêt pour la poésie",
    image: "/images/events/event1.jpg",
    startDate: "2025-12-15",
    endDate: "2025-12-15",
    startTime: "14:00",
    endTime: "16:00",
    location: "Salle de Danse Principale",
    discipline: "Atelier",
  },
  {
    id: "16",
    slug: "rencontres-litteraires",
    title: "Rencontres littéraires",
    category: "Littérature & Pensée",
    categorySlug: "litterature-pensee",
    slogan: "Dialogue autour du livre",
    description:
      "Un espace de dialogue entre écrivains, éditeurs et lecteurs pour promouvoir la littérature congolaise et africaine.",
    objectif: "Créer des espaces d'échange autour de la littérature",
    publicVise: "Écrivains, lecteurs, éditeurs, bibliothécaires",
    impact: "Dynamisation du secteur du livre",
    image: "/images/media/media7.jpg",
    startDate: "2025-12-15",
    endDate: "2025-12-15",
    startTime: "14:00",
    endTime: "16:00",
    location: "Salle de Danse Principale",
    featured: true,
    discipline: "Atelier",
  },
  {
    id: "17",
    slug: "pensee-panafricaine",
    title: "Pensée panafricaine",
    category: "Littérature & Pensée",
    categorySlug: "litterature-pensee",
    slogan: "Réflexion sur l'avenir de l'Afrique",
    description:
      "Forum réunissant chercheurs, artistes, écrivains et acteurs autour des grands thèmes du panafricanisme contemporain. ",
    objectif: "Stimuler la réflexion intellectuelle sur l'Afrique",
    publicVise: "Intellectuels, étudiants, décideurs, société civile",
    impact: "Contribution au débat panafricain",
    image: "/images/events/event1.jpg",
    startDate: "2025-12-15",
    endDate: "2025-12-15",
    startTime: "14:00",
    endTime: "16:00",
    location: "Salle de Danse Principale",
    discipline: "Atelier",
  },
  {
    id: "18",
    slug: "journees-image-femme-africaine",
    title: "Journées de l'Image de la Femme Africaine",
    category: "Littérature & Pensée",
    categorySlug: "litterature-pensee",
    slogan: "Célébration de la femme africaine",
    description:
      "Rencontres, projections et débats autour de la représentation des femmes dans les médias et arts visuels. ",
    objectif: "Valoriser le rôle et l'image de la femme dans la société",
    publicVise: "Femmes artistes, associations féminines, grand public",
    impact: "Changement des représentations et empowerment",
    image: "/images/events/event1.jpg",
    startDate: "2025-12-15",
    endDate: "2025-12-15",
    startTime: "14:00",
    endTime: "16:00",
    location: "Salle de Danse Principale",
    discipline: "Atelier",
  },
  {
    id: "19",
    slug: "territoires",
    title: "Territoires – Traditions de la RDC",
    category: "Littérature & Pensée",
    categorySlug: "litterature-pensee",
    slogan: "Exploration des identités culturelles",
    description:
      "Programme annuel valorisant coutumes, langues, danses et musiques de chaque région. ",
    objectif: "Cartographier la diversité culturelle congolaise",
    publicVise: "Chercheurs, communautés locales, étudiants",
    impact: "Documentation des pratiques culturelles locales",
    image: "/images/media/media8.jpg",
    startDate: "2025-12-15",
    endDate: "2025-12-15",
    startTime: "14:00",
    endTime: "16:00",
    location: "Salle de Danse Principale",
    discipline: "Atelier",
    featured: true,
  },
  {
    id: "20",
    slug: "450-gouts-pondu",
    title: "Les 450 goûts de Pondu",
    category: "Littérature & Pensée",
    categorySlug: "litterature-pensee",
    slogan: "Patrimoine culinaire congolais",
    description:
      "Festival culinaire mettant en valeur le saka-saka, décliné en centaines de recettes régionales. ",
    objectif: "Documenter et promouvoir le patrimoine culinaire",
    publicVise: "Cuisiniers, familles, chercheurs en anthropologie",
    impact: "Préservation des recettes traditionnelles",
    image: "/images/events/event1.jpg",
    startDate: "2025-12-15",
    endDate: "2025-12-15",
    startTime: "14:00",
    endTime: "16:00",
    location: "Salle de Danse Principale",
    discipline: "Atelier",
  },
  {
    id: "21",
    slug: "route-rumba",
    title: "Route de la Rumba",
    category: "Littérature & Pensée",
    categorySlug: "litterature-pensee",
    slogan: "Sur les traces de la rumba",
    description:
      "Biennale retraçant les voyages des racines congolaises, symbole du lien avec la diaspora.",
    objectif:
      "Créer un itinéraire touristique et culturel de la rumba congolaise",
    publicVise: "Touristes, mélomanes, historiens",
    impact: "Développement du tourisme culturel",
    image: "/images/events/event1.jpg",
    startDate: "2025-12-15",
    endDate: "2025-12-15",
    startTime: "14:00",
    endTime: "16:00",
    location: "Salle de Danse Principale",
    discipline: "Atelier",
  },
  {
    id: "22",
    slug: "parole-vivante",
    title: "Festival de la Parole vivante",
    category: "Littérature & Pensée",
    categorySlug: "litterature-pensee",
    slogan: "Transmission orale des savoirs",
    description:
      "Dédié aux arts oratoires et à la littérature orale congolaise et africaine, mémoire et transmission des valeurs. ",
    objectif: "Préserver les traditions orales congolaises",
    publicVise: "Anciens, jeunes, chercheurs, communautés",
    impact: "Sauvegarde du patrimoine immatériel",
    image: "/images/events/event1.jpg",
    startDate: "2025-12-15",
    endDate: "2025-12-15",
    startTime: "14:00",
    endTime: "16:00",
    location: "Salle de Danse Principale",
    discipline: "Atelier",
  },
  {
    id: "23",
    slug: "langues-nationales",
    title: "Langues nationales ",
    category: "Littérature & Pensée",
    categorySlug: "litterature-pensee",
    slogan: "Sagesse ancestrale",
    description:
      "Programme d’apprentissage du lingala, kikongo, swahili et tshiluba pour renforcer l’identité culturelle. ",
    objectif: "Valoriser les langues comme acteurs de l'identité culturelle",
    publicVise: "Communautés traditionnelles, jeunes, éducateurs",
    impact: "Lutte contre l'érosion linguistique",
    image: "/images/events/event1.jpg",
    startDate: "2025-12-15",
    endDate: "2025-12-15",
    startTime: "14:00",
    endTime: "16:00",
    location: "Salle de Danse Principale",
    discipline: "Atelier",
  },
  {
    id: "24",
    slug: "contes-chants-proverbes",
    title: "Ateliers intergénérationnels",
    category: "Littérature & Pensée",
    categorySlug: "litterature-pensee",
    slogan: "Trésors de l'oralité",
    description:
      "Espaces d’expression artistique pour enfants et jeunes, développant discipline, confiance et solidarité. ",
    objectif:
      "Favoriser le développement de la créativité et de la solidarité entre les générations",
    publicVise: "Enfants, familles, enseignants, chercheurs",
    impact: "Enrichissement de l'éducation culturelle",
    image: "/images/events/event1.jpg",
    startDate: "2025-12-15",
    endDate: "2025-12-15",
    startTime: "14:00",
    endTime: "16:00",
    location: "Salle de Danse Principale",
    discipline: "Atelier",
  },
  // {
  //   id: "25",
  //   slug: "ateliers-transmission",
  //   title: "Ateliers de transmission intergénérationnelle",
  //   category: "Littérature & Pensée",
  //   categorySlug: "litterature-pensee",
  //   slogan: "Apprendre en faisant",
  //   description: "Ateliers pratiques de transmission des savoir-faire",
  //   objectif:
  //     "Former aux techniques artisanales et artistiques traditionnelles",
  //   publicVise: "Jeunes, artisans, artistes, éducateurs",
  //   impact: "Pérennisation des savoir-faire traditionnels",
  //   startDate: "2025-12-15",
  //   endDate: "2025-12-15",
  //   startTime: "14:00",
  //   endTime: "16:00",
  //   location: "Salle de Danse Principale",
  //   discipline: "Atelier",
  //   image: "/images/events/event1.jpg",
  // },
];

export function getProgrammesByCategory(categorySlug: string): Programme[] {
  return programmes.filter((p) => p.categorySlug === categorySlug);
}

export function getProgrammeBySlug(slug: string): Programme | undefined {
  return programmes.find((p) => p.slug === slug);
}

export function getFeaturedProgrammes(): Programme[] {
  return programmes.filter((p) => p.featured);
}
